name: ontime
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  intl: any
  get: ^4.7.2
  get_storage: ^2.1.1
  dartz: ^0.10.1
  easy_localization: ^3.0.8
  flutter_svg: ^2.2.1
  flutter_dotenv: ^6.0.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.12.0
  build_runner: ^2.9.0
  

# FlutterGen configuration
flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true


flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/icons/auth/
    - assets/icons/buttons/
    - assets/icons/categories/
    - assets/icons/navigation/
    - assets/icons/provider/
    - assets/icons/social/
    - assets/icons/status/
    - assets/icons/ui/
    - assets/translations/  
  
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato/Lato-Light.ttf
          weight: 500
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700